// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fall back to the file-backed dev database so `prisma migrate`
    // commands work out of the box (including in CI, which provides no
    // DATABASE_URL). Mirrors the runtime fallback in
    // src/prisma/prisma.service.ts.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
