export enum NotificationType {
  CLAIM_SUBMITTED = 'CLAIM_SUBMITTED',
  VERIFICATION_ASSIGNED = 'VERIFICATION_ASSIGNED',
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  REWARDS_DISTRIBUTED = 'REWARDS_DISTRIBUTED',
  GOVERNANCE_PROPOSAL_CREATED = 'GOVERNANCE_PROPOSAL_CREATED',
  GOVERNANCE_VOTING_REMINDER = 'GOVERNANCE_VOTING_REMINDER',
  REPUTATION_UPDATE = 'REPUTATION_UPDATE',
  STAKING_EVENT = 'STAKING_EVENT',
  TREASURY_ANNOUNCEMENT = 'TREASURY_ANNOUNCEMENT',
  MODERATOR_ACTION = 'MODERATOR_ACTION',
  SECURITY_ALERT = 'SECURITY_ALERT',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
}

export enum DeliveryChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  WEBHOOK = 'WEBHOOK',
  PUSH = 'PUSH',
  SMS = 'SMS',
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationFrequency {
  INSTANT = 'INSTANT',
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
}