export enum NotificationCategory {
  CLAIM = 'CLAIM',
  VERIFICATION = 'VERIFICATION',
  DISPUTE = 'DISPUTE',
  GOVERNANCE = 'GOVERNANCE',
  REWARD = 'REWARD',
  REPUTATION = 'REPUTATION',
  MODERATION = 'MODERATION',
  SYSTEM = 'SYSTEM',
}
